### ISSUE TITLE
InlineAbbreviations.pdf 

### ISSUE THREAD

**Issue by hhrutter** [pdf-association/safedocs#3]
Hi!

I downloaded InlineAbbreviations.pdf and it does not open regardless if I try with Mac Preview or Adobe Reader
although github does render it correctly.

**Comment by petervwyatt** [comment]
Be careful that your downloading process isn't scrambling line endings as might get auto-confused as text (since I made the PDF text editor compatible so there are no binary bytes). Or your A/V is triggering and altering the file. Try downloading the ZIP of the repo directly and just extracting from there.

I don't own a Mac, but I have no problems opening it with the following (in no specific order) on PC/Windows 10 and, for some of these, WSL2 Ubuntu via XWindows and on a native Ubuntu box: Adobe Acrobat, PDF XChange, Nitro, Foxit, PDF Studio Viewer, Javelin3, Slim PDF Reader, PDF Architect, Xodo, MuPDF, GS, Chrome, FireFox, Edge, Xpdf, PDFBox Debugger app. Output, of course, varies.

**Comment by hhrutter** [comment]
I am just downloading the file using Chrome.
Only If I click on the file and let Github render it and then click on `Raw` the download is fine otherwise I get some weird html.

**Comment by petervwyatt** [comment]
That's how GitHub works - the same thing happens with MD, source code or any other file. The HTML is the GH page for the file, not the file itself. You always need to use the Raw to get file.
