### ISSUE TITLE
Invalid `CompactedPDFSyntaxTest.pdf`: The `/Info` dictionary needs to be an indirect object

### ISSUE THREAD

**Issue by gettalong** [pdf-association/safedocs#5]
According to the specification, the `/Info` key in the trailer dictionary *"shall be an indirect reference"* (see https://www.iso.org/foreword-supplementary-information.html for the use of "shall" in ISO specs).

You have included the info dictionary directly in the trailer and therefore the PDF is invalid.

**Comment by petervwyatt** [comment]
You are technically correct. Thank you for highlighting.

As I'm sure you are aware there are many extant PDFs that also do not comply with this technicality. See also https://github.com/pdf-association/pdf-issues/issues/106 "_Mandated indirect reference requirements not followed and not enforced - are they really requirements_?"

**Comment by petervwyatt** [comment]
As reported by the Arlington PDF Model:
`Error: not an indirect reference as required: Info ("FileTrailer")`

**Comment by gettalong** [comment]
> As I'm sure you are aware there are many extant PDFs that also do not comply with this technicality. See also [pdf-association/pdf-issues#106](https://github.com/pdf-association/pdf-issues/issues/106) "_Mandated indirect reference requirements not followed and not enforced - are they really requirements_?"

Yes, I'm aware. However, I don't think that the PDF specification should be weakened to support PDF libraries that produce invalid PDFs. Then we would potentially end up with the same hodgepodge that is HTML5. The difference to HTML is that PDF can't just be written by anyone with a text editor but one needs a PDF library.

**Comment by petervwyatt** [comment]
Unlike for HTML, the root problem for general PDF is that there is no independent validator that implementers can use that can tell them when they introduce errors in files. PDF creators then rely on the exceedingly loose "_it works in my PDF viewer_" as their validity criteria and this subsequently requires all other PDF viewers/renders/processors to get "permissive" in order to support those invalid files. Some of the biggest vendors in the world create technically invalid PDFs. And then the spec words become far less meaningful as they are not enforced by either PDF writer or PDF readers implementations (for general-purpose PDF, not PDF subsets) so it becomes a vicious cycle...

**Comment by gettalong** [comment]
> Unlike for HTML, the root problem for general PDF is that there is no independent validator that implementers can use that can tell them when they introduce errors in files.

But isn't that a rather easy problem to solve? Many tools, including qpdf and my own PDF library HexaPDF, have functionality to check the validity of a PDF file which is how I found the problem with the test PDF. If the PDF Association would create a web-based validator I think that would count as "independent".

And it is not necessary to be 100% correct in the analysis of a PDF file. Just stating "If an error is found, the PDF is surely invalid. However, due to the validator being in constant development, some errors might not yet be found" should get the ball rolling.

> PDF creators then rely on the exceedingly loose "it works in my PDF viewer" as their validity criteria

Yeah, Adobe (?) probably shouldn't have started this trend...

But I don't think that updating the PDF spec to make this invalid PDFs valid is an appropriate solution. Wouldn't it be better to include wording that states that a message should be displayed to the user if an invalid but repaired PDF was viewed/processed? This would make it an incentive for PDF writers to produce valid PDFs.

**Comment by MatthiasValvekens** [comment]
At risk of sounding pedantic:

 - Both parts of the PDF standard (ISO 32000) exclude conformance validation from their own scope, so unless that changes, including any wording to tell interactive processors what to do when they encounter an invalid PDF is unfortunately not an option. In general, the committee is also quite averse towards including user experience requirements.
 - Whatever a valid PDF is is _defined_ by the standard (at least, for PDF 1.7 and PDF 2.0), and there have been changes and/or bug fixes that would make previously invalid files valid in the past. I'm not sure changing the rules on whether **Info** is required to be indirect or not is all that different. Granted, none of that matters for this particular file, since right now the rules still say that the value of **Info** has to be indirect. :)

**Comment by petervwyatt** [comment]
File was fixed yesterday 😁

And, yes, a big philosophical difference with PDF specs to date vs HTML is that PDF doesn't have a clause like https://html.spec.whatwg.org/#syntax-errors. But we could definitely create a lengthy parallel publication to https://htmlparser.info/ for PDF...

**Comment by MatthiasValvekens** [comment]
> But we could definitely create a lengthy parallel publication to https://htmlparser.info/ for PDF...

Ouch... Both technically and "politically" (for lack of a better term) that sounds like an uphill battle. 😅
